volumes:
  todos-vol:

services:
  pgsql:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword # environment variable that sets the superuser password for PostgreSQL
      POSTGRES_USER: mario # variable that will create the specified user
      POSTGRES_DB: todos # the name of your db
    volumes:
      - todos-vol:/var/lib/postgresql/data
    ports:
      - 5432:5432
